//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBook()
        {
            this.TAuthorHasBook = new HashSet<TAuthorHasBook>();
        }
    
        public int iSBN { get; set; }
        public int idEditorial { get; set; }
        public string title { get; set; }
        public string synopsis { get; set; }
        public string pages { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAuthorHasBook> TAuthorHasBook { get; set; }
        public virtual TEditorial TEditorial { get; set; }
    }
}
