//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBook
    {
        public int iSBN { get; set; }
        public int idEditorial { get; set; }
        public string title { get; set; }
        public string synopsis { get; set; }
        public string pages { get; set; }
    
        public virtual TEditorial TEditorial { get; set; }
    }
}
